# Generated by Django 4.2.7 on 2023-11-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last',
        ),
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='origin',
            field=models.CharField(default='userpass', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.CharField>/profile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='userID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
