# Generated by Django 4.2.6 on 2024-01-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_member_about_alter_member_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='origin',
        ),
        migrations.CreateModel(
            name='gLogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googleID', models.CharField(max_length=255, unique=True)),
                ('pointTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
    ]
