# Generated by Django 4.2.6 on 2024-01-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_member_origin_glogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='userID',
        ),
    ]
