# Generated by Django 4.2.6 on 2024-02-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_member_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glogin',
            old_name='pointTo',
            new_name='referTo',
        ),
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (99, 'admin'), (1, 'member'), (2, 'trusted member')], default=1),
        ),
    ]
