# Generated by Django 4.2.6 on 2024-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (99, 'admin'), (1, 'member'), (2, 'trusted member')], default=1),
        ),
    ]
