# Generated by Django 4.2.6 on 2024-02-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_member_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=75)),
                ('displayname', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(1, 'member'), (99, 'admin'), (98, 'moderator'), (2, 'trusted member')], default=1),
        ),
    ]
