# Generated by Django 4.2.6 on 2024-03-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (1, 'member'), (99, 'admin'), (-1, 'banned'), (2, 'trusted member')], default=1),
        ),
    ]
