# Generated by Django 4.2.6 on 2024-03-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (2, 'trusted member'), (98, 'moderator'), (99, 'admin'), (1, 'member')], default=1),
        ),
    ]
