# Generated by Django 4.2.6 on 2024-03-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (1, 'member'), (-1, 'banned'), (99, 'admin'), (98, 'moderator')], default=1),
        ),
    ]
