<<<<<<< HEAD
# Generated by Django 4.2.16 on 2025-03-31 18:32
=======
# Generated by Django 4.2.16 on 2025-02-24 21:08
>>>>>>> b4bf70dd41b282f4bbe675fc57a32500531620c3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (98, 'moderator'), (-1, 'banned'), (1, 'member'), (99, 'admin')], default=1),
=======
            field=models.SmallIntegerField(choices=[(1, 'member'), (99, 'admin'), (2, 'trusted member'), (-1, 'banned'), (98, 'moderator')], default=1),
>>>>>>> b4bf70dd41b282f4bbe675fc57a32500531620c3
        ),
    ]
