# Generated by Django 4.2.16 on 2025-03-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (98, 'moderator'), (-1, 'banned'), (1, 'member'), (99, 'admin')], default=1),
        ),
    ]
