<<<<<<<<< Temporary merge branch 1
# Generated by Django 4.2.16 on 2025-03-31 18:32
=========
# Generated by Django 4.2.16 on 2025-02-24 21:08
>>>>>>>>> Temporary merge branch 2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<<<< Temporary merge branch 1
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (98, 'moderator'), (-1, 'banned'), (1, 'member'), (99, 'admin')], default=1),
=========
            field=models.SmallIntegerField(choices=[(1, 'member'), (99, 'admin'), (2, 'trusted member'), (-1, 'banned'), (98, 'moderator')], default=1),
>>>>>>>>> Temporary merge branch 2
        ),
    ]
