# Generated by Django 4.2.16 on 2025-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (98, 'moderator'), (2, 'trusted member'), (1, 'member'), (99, 'admin')], default=1),
        ),
    ]
