<<<<<<< HEAD
# Generated by Django 4.2.16 on 2025-04-07 19:23
=======
# Generated by Django 4.2.16 on 2025-02-26 20:44
>>>>>>> b4bf70dd41b282f4bbe675fc57a32500531620c3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (98, 'moderator'), (1, 'member'), (99, 'admin'), (-1, 'banned')], default=1),
=======
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (2, 'trusted member'), (1, 'member'), (98, 'moderator'), (99, 'admin')], default=1),
>>>>>>> b4bf70dd41b282f4bbe675fc57a32500531620c3
        ),
    ]
