<<<<<<< HEAD
# Generated by Django 4.2.16 on 2025-04-07 19:50
=======
# Generated by Django 4.2.16 on 2025-02-26 21:02
>>>>>>> integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(99, 'admin'), (98, 'moderator'), (-1, 'banned'), (1, 'member'), (2, 'trusted member')], default=1),
=======
            field=models.SmallIntegerField(choices=[(99, 'admin'), (1, 'member'), (-1, 'banned'), (2, 'trusted member'), (98, 'moderator')], default=1),
>>>>>>> integration
        ),
    ]
