# Generated by Django 4.2.16 on 2025-02-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(99, 'admin'), (98, 'moderator'), (2, 'trusted member'), (-1, 'banned'), (1, 'member')], default=1),
        ),
    ]
