# Generated by Django 4.2.16 on 2025-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(1, 'member'), (98, 'moderator'), (99, 'admin'), (-1, 'banned'), (2, 'trusted member')], default=1),
        ),
    ]
