# Generated by Django 4.2.16 on 2025-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (2, 'trusted member'), (99, 'admin'), (1, 'member'), (98, 'moderator')], default=1),
        ),
    ]
