<<<<<<< HEAD
# Generated by Django 4.2.16 on 2025-04-09 20:14
=======
# Generated by Django 4.2.16 on 2025-03-03 20:24
>>>>>>> b4bf70dd41b282f4bbe675fc57a32500531620c3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(1, 'member'), (-1, 'banned'), (99, 'admin'), (98, 'moderator'), (2, 'trusted member')], default=1),
=======
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (2, 'trusted member'), (99, 'admin'), (1, 'member'), (98, 'moderator')], default=1),
>>>>>>> b4bf70dd41b282f4bbe675fc57a32500531620c3
        ),
    ]
