# Generated by Django 4.2.6 on 2025-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (99, 'admin'), (1, 'member'), (98, 'moderator'), (2, 'trusted member')], default=1),
        ),
    ]
