# Generated by Django 4.2.19 on 2025-10-22 19:46

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_member_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
