# Generated by Django 5.2.6 on 2025-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (-1, 'banned'), (2, 'trusted member'), (99, 'admin'), (1, 'member')], default=1),
        ),
    ]
