# Generated by Django 4.2.19 on 2025-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20251022_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(99, 'admin'), (1, 'member'), (98, 'moderator'), (-1, 'banned'), (2, 'trusted member')], default=1),
        ),
    ]
