# Generated by Django 5.2.6 on 2025-09-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (99, 'admin'), (98, 'moderator'), (2, 'trusted member'), (1, 'member')], default=1),
        ),
    ]
