# Generated by Django 4.2.6 on 2026-03-09 19:45

import account.models
import account.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_add_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(default='default/blankprof.png', storage=account.storage.OverwriteStorage(), upload_to=account.models.user_directory_profile),
        ),
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (1, 'member'), (99, 'admin'), (98, 'moderator'), (-1, 'banned')], default=1),
        ),
    ]
