# Generated by Django 4.2.6 on 2026-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20251022_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (2, 'trusted member'), (99, 'admin'), (1, 'member'), (-1, 'banned')], default=1),
        ),
    ]
