# Generated by Django 4.2.6 on 2026-03-01 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20251022_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(99, 'admin'), (98, 'moderator'), (2, 'trusted member'), (1, 'member'), (-1, 'banned')], default=1),
        ),
    ]
