# Generated by Django 4.2.19 on 2025-11-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_member_ranking'),
        ('account', '0032_auto_20251022_2002'),
    ]

    operations = [
    ]
