# Generated by Django 4.2.6 on 2026-03-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_member_created_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(99, 'admin'), (1, 'member'), (2, 'trusted member'), (-1, 'banned'), (98, 'moderator')], default=1),
        ),
    ]
