<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-03-01 22:24
=======
# Generated by Django 4.2.6 on 2026-03-09 20:21
>>>>>>> integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('account', '0034_alter_member_created_alter_member_ranking'),
=======
        ('account', '0034_alter_member_ranking'),
>>>>>>> integration
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (1, 'member'), (99, 'admin'), (-1, 'banned'), (2, 'trusted member')], default=1),
=======
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (1, 'member'), (99, 'admin'), (-1, 'banned'), (98, 'moderator')], default=1),
>>>>>>> integration
        ),
    ]
