# Generated by Django 4.2.6 on 2026-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (1, 'member'), (99, 'admin'), (-1, 'banned'), (98, 'moderator')], default=1),
        ),
    ]
