# Generated by Django 4.2.6 on 2026-04-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_member_ranking'),
        ('account', '0035_alter_member_ranking'),
    ]

    operations = [
    ]
