# Generated by Django 4.2.6 on 2026-03-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (1, 'member'), (98, 'moderator'), (99, 'admin'), (-1, 'banned')], default=1),
        ),
    ]
