<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-04-20 00:45
=======
# Generated by Django 4.2.6 on 2026-03-30 19:55
>>>>>>> integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('account', '0036_merge_20260406_1626'),
=======
        ('account', '0036_alter_member_ranking'),
>>>>>>> integration
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(99, 'admin'), (2, 'trusted member'), (1, 'member'), (98, 'moderator'), (-1, 'banned')], default=1),
=======
            field=models.SmallIntegerField(choices=[(-1, 'banned'), (2, 'trusted member'), (98, 'moderator'), (1, 'member'), (99, 'admin')], default=1),
>>>>>>> integration
        ),
    ]
