# Generated by Django 4.2.6 on 2026-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (98, 'moderator'), (-1, 'banned'), (99, 'admin'), (1, 'member')], default=1),
        ),
    ]
