<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-03-30 20:56
=======
# Generated by Django 4.2.6 on 2026-04-20 00:50
>>>>>>> development

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(99, 'admin'), (-1, 'banned'), (2, 'trusted member'), (98, 'moderator'), (1, 'member')], default=1),
=======
            field=models.SmallIntegerField(choices=[(1, 'member'), (99, 'admin'), (-1, 'banned'), (98, 'moderator'), (2, 'trusted member')], default=1),
>>>>>>> development
        ),
    ]
