# Generated by Django 4.2.6 on 2026-03-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_member_ranking'),
        ('account', '0037_alter_member_ranking'),
    ]

    operations = [
    ]
