<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-04-20 00:57
=======
# Generated by Django 4.2.6 on 2026-04-01 19:14
>>>>>>> integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(99, 'admin'), (2, 'trusted member'), (-1, 'banned'), (98, 'moderator'), (1, 'member')], default=1),
=======
            field=models.SmallIntegerField(choices=[(99, 'admin'), (98, 'moderator'), (-1, 'banned'), (2, 'trusted member'), (1, 'member')], default=1),
>>>>>>> integration
        ),
    ]
