# Generated by Django 4.2.19 on 2026-03-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(1, 'member'), (2, 'trusted member'), (99, 'admin'), (-1, 'banned'), (98, 'moderator')], default=1),
        ),
    ]
