# Generated by Django 4.2.19 on 2026-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(99, 'admin'), (2, 'trusted member'), (98, 'moderator'), (-1, 'banned'), (1, 'member')], default=1),
        ),
    ]
