# Generated by Django 4.2.19 on 2026-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (1, 'member'), (-1, 'banned'), (98, 'moderator'), (99, 'admin')], default=1),
        ),
    ]
