<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-04-29 19:15
=======
# Generated by Django 4.2.6 on 2026-04-10 23:52
>>>>>>> integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(99, 'admin'), (1, 'member'), (98, 'moderator'), (2, 'trusted member'), (-1, 'banned')], default=1),
=======
            field=models.SmallIntegerField(choices=[(2, 'trusted member'), (98, 'moderator'), (99, 'admin'), (-1, 'banned'), (1, 'member')], default=1),
>>>>>>> integration
        ),
    ]
