<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-04-10 23:53
=======
# Generated by Django 4.2.6 on 2026-04-01 20:10
>>>>>>> development

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(1, 'member'), (98, 'moderator'), (2, 'trusted member'), (-1, 'banned'), (99, 'admin')], default=1),
=======
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (-1, 'banned'), (99, 'admin'), (2, 'trusted member'), (1, 'member')], default=1),
>>>>>>> development
        ),
    ]
