# Generated by Django 4.2.6 on 2026-04-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (-1, 'banned'), (99, 'admin'), (2, 'trusted member'), (1, 'member')], default=1),
        ),
    ]
