# Generated by Django 4.2.6 on 2026-04-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(98, 'moderator'), (99, 'admin'), (1, 'member'), (2, 'trusted member'), (-1, 'banned')], default=1),
        ),
    ]
