# Generated by Django 4.2.6 on 2026-04-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(99, 'admin'), (2, 'trusted member'), (-1, 'banned'), (1, 'member'), (98, 'moderator')], default=1),
        ),
    ]
