# Generated by Django 4.2.6 on 2026-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(99, 'admin'), (-1, 'banned'), (98, 'moderator'), (1, 'member'), (2, 'trusted member')], default=1),
        ),
    ]
