# Generated by Django 4.2.6 on 2026-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_alter_member_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.SmallIntegerField(choices=[(1, 'member'), (-1, 'banned'), (98, 'moderator'), (2, 'trusted member'), (99, 'admin')], default=1),
        ),
    ]
