# Generated by Django 4.2.6 on 2023-11-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='no subject', max_length=75),
            preserve_default=False,
        ),
    ]
