# Generated by Django 4.2.6 on 2024-02-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0002_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
