# Generated by Django 4.2.6 on 2024-02-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_member_ranking'),
        ('Janitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='user',
        ),
        migrations.AddField(
            model_name='userreport',
            name='account',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='account.member'),
            preserve_default=False,
        ),
    ]
