# Generated by Django 4.2.6 on 2024-03-06 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    #replaces = [('mapViewer', '0001_initial'), ('mapViewer', '0002_maptag_mappost'), ('mapViewer', '0003_rename_tagname_maptag_name_alter_mappost_tags'), ('mapViewer', '0004_alter_maptag_name'), ('mapViewer', '0005_mappost_geocode'), ('mapViewer', '0006_remove_mappost_latitude_remove_mappost_longitude'), ('mapViewer', '0007_delete_mapwidget_remove_mappost_isvisible_and_more')]

    initial = True

    dependencies = [
        ('account', '0010_alter_member_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='mapViewer.maptag')),
                ('geoCode', models.JSONField(default=[])),
                ('visibility', models.SmallIntegerField(choices=[(-1, 'denied'), (2, 'visible'), (0, 'pending')], default=0)),
            ],
        ),
    ]
