# Generated by Django 4.2.6 on 2024-02-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0002_maptag_mappost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maptag',
            old_name='tagName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='mappost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='mapViewer.maptag'),
        ),
    ]
