# Generated by Django 4.2.6 on 2025-04-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0003_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'visible'), (-1, 'denied')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(1, 'video'), (0, 'image'), (2, 'audio')], default=0),
        ),
    ]
