# Generated by Django 4.2.6 on 2024-02-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0003_rename_tagname_maptag_name_alter_mappost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maptag',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
