<<<<<<< HEAD
# Generated by Django 4.2.16 on 2025-10-06 20:04
=======
# Generated by Django 4.2.19 on 2025-11-19 15:53
>>>>>>> integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0004_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(2, 'audio'), (1, 'video'), (0, 'image')], default=0),
=======
            field=models.SmallIntegerField(choices=[(2, 'audio'), (0, 'image'), (1, 'video')], default=0),
>>>>>>> integration
        ),
    ]
