# Generated by Django 4.2.19 on 2025-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0004_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'visible'), (0, 'pending'), (-1, 'denied')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(2, 'audio'), (1, 'video'), (0, 'image')], default=0),
        ),
    ]
