# Generated by Django 4.2.6 on 2025-10-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0004_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(1, 'video'), (2, 'audio'), (0, 'image')], default=0),
        ),
    ]
