# Generated by Django 4.2.6 on 2024-02-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0004_alter_maptag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappost',
            name='geoCode',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
