# Generated by Django 4.2.6 on 2024-02-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0005_mappost_geocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='mappost',
            name='longitude',
        ),
    ]
