<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-03-09 19:45
=======
# Generated by Django 4.2.16 on 2025-10-20 20:16
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0005_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (-1, 'denied'), (1, 'visible')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(0, 'image'), (1, 'video'), (2, 'audio')], default=0),
=======
            field=models.SmallIntegerField(choices=[(1, 'video'), (2, 'audio'), (0, 'image')], default=0),
>>>>>>> main
        ),
    ]
