# Generated by Django 4.2.16 on 2026-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0006_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(2, 'audio'), (1, 'video'), (0, 'image')], default=0),
        ),
    ]
