# Generated by Django 4.2.6 on 2026-03-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0006_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(0, 'image'), (1, 'video'), (2, 'audio')], default=0),
        ),
    ]
