# Generated by Django 4.2.6 on 2024-03-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0001_0007_squash_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='geoCode',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (1, 'visible'), (0, 'pending')], default=0),
        ),
    ]
