# Generated by Django 4.2.6 on 2026-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0007_alter_forum_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (-1, 'denied'), (1, 'visible')], default=0),
        ),
    ]
