# Generated by Django 4.2.6 on 2026-03-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0008_alter_forum_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'visible'), (0, 'pending'), (-1, 'denied')], default=0),
        ),
    ]
