# Generated by Django 4.2.19 on 2026-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0009_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'visible'), (-1, 'denied')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(0, 'image'), (2, 'audio'), (1, 'video')], default=0),
        ),
    ]
