# Generated by Django 4.2.6 on 2026-03-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0007_alter_forum_visibility_alter_media_format'),
        ('mapViewer', '0009_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
    ]
