# Generated by Django 4.2.6 on 2024-03-18 20:15

from django.db import migrations, models
import django.db.models.deletion
import mapViewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0010_alter_mappost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (1, 'visible'), (0, 'pending')], default=0),
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mapViewer.models.post_file_directory)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapViewer.mappost')),
            ],
        ),
    ]
