# Generated by Django 4.2.6 on 2026-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0010_merge_20260330_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='forum',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (-1, 'denied'), (1, 'visible')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(0, 'image'), (1, 'video'), (2, 'audio')], default=0),
        ),
    ]
