# Generated by Django 4.2.16 on 2025-02-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0010_alter_mappost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
        ),
    ]
