# Generated by Django 4.2.6 on 2024-03-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0011_alter_mappost_visibility_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='extension',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (-1, 'denied'), (1, 'visible')], default=0),
        ),
    ]
