# Generated by Django 4.2.19 on 2026-03-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0011_alter_forum_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'visible'), (-1, 'denied')], default=0),
        ),
    ]
