# Generated by Django 4.2.6 on 2024-03-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0012_postfile_extension_alter_mappost_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='extension',
        ),
        migrations.AddField(
            model_name='postfile',
            name='format',
            field=models.SmallIntegerField(choices=[(0, 'image'), (2, 'audio'), (1, 'video')], default=0),
        ),
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
        ),
    ]
