# Generated by Django 4.2.6 on 2026-03-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0012_alter_forum_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (1, 'visible'), (0, 'pending')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(1, 'video'), (2, 'audio'), (0, 'image')], default=0),
        ),
    ]
