# Generated by Django 4.2.16 on 2025-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0013_alter_mappost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'visible'), (-1, 'denied')], default=0),
        ),
    ]
