# Generated by Django 4.2.6 on 2024-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0013_remove_postfile_extension_postfile_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='format',
            field=models.SmallIntegerField(choices=[(1, 'video'), (0, 'image'), (2, 'audio')], default=0),
        ),
    ]
