<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-04-06 20:06
=======
<<<<<<<< HEAD:cccSite/mapViewer/migrations/0006_alter_forum_visibility_alter_media_format.py
# Generated by Django 4.2.16 on 2025-10-20 20:16
========
<<<<<<< HEAD
# Generated by Django 4.2.16 on 2026-04-15 20:08
=======
# Generated by Django 4.2.19 on 2026-04-16 19:53
>>>>>>> development
>>>>>>>> development:cccSite/mapViewer/migrations/0015_alter_forum_visibility_alter_media_format.py
>>>>>>> development

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0014_alter_forum_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(1, 'visible'), (-1, 'denied'), (0, 'pending')], default=0),
=======
<<<<<<<< HEAD:cccSite/mapViewer/migrations/0006_alter_forum_visibility_alter_media_format.py
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
========
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(0, 'pending'), (-1, 'denied'), (1, 'visible')], default=0),
=======
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
>>>>>>> development
>>>>>>>> development:cccSite/mapViewer/migrations/0015_alter_forum_visibility_alter_media_format.py
>>>>>>> development
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(2, 'audio'), (1, 'video'), (0, 'image')], default=0),
=======
<<<<<<<< HEAD:cccSite/mapViewer/migrations/0006_alter_forum_visibility_alter_media_format.py
            field=models.SmallIntegerField(choices=[(0, 'image'), (1, 'video'), (2, 'audio')], default=0),
========
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(1, 'video'), (0, 'image'), (2, 'audio')], default=0),
=======
            field=models.SmallIntegerField(choices=[(0, 'image'), (2, 'audio'), (1, 'video')], default=0),
>>>>>>> development
>>>>>>>> development:cccSite/mapViewer/migrations/0015_alter_forum_visibility_alter_media_format.py
>>>>>>> development
        ),
    ]
