# Generated by Django 4.2.16 on 2026-04-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0014_alter_forum_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (-1, 'denied'), (1, 'visible')], default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(1, 'video'), (0, 'image'), (2, 'audio')], default=0),
        ),
    ]
