# Generated by Django 4.2.6 on 2026-04-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0014_alter_forum_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.SmallIntegerField(choices=[(2, 'audio'), (0, 'image'), (1, 'video')], default=0),
        ),
    ]
