# Generated by Django 5.2.6 on 2025-09-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0016_alter_mappost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'visible'), (-1, 'denied'), (0, 'pending')], default=0),
        ),
    ]
