# Generated by Django 4.2.6 on 2026-04-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0015_alter_media_format'),
        ('mapViewer', '0017_alter_forum_visibility_alter_media_format'),
    ]

    operations = [
    ]
