<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-04-20 00:45
=======
# Generated by Django 4.2.6 on 2026-03-11 19:26
>>>>>>> development

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0019_alter_mappost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(1, 'visible'), (-1, 'denied'), (0, 'pending')], default=0),
=======
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
>>>>>>> development
        ),
    ]
