# Generated by Django 4.2.6 on 2026-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0021_alter_mappost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (1, 'visible'), (0, 'pending')], default=0),
        ),
    ]
