<<<<<<< HEAD
# Generated by Django 4.2.6 on 2026-04-20 00:57
=======
# Generated by Django 4.2.6 on 2026-03-25 19:52
>>>>>>> development

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0021_alter_mappost_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappost',
            name='visibility',
<<<<<<< HEAD
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (0, 'pending'), (1, 'visible')], default=0),
=======
            field=models.SmallIntegerField(choices=[(-1, 'denied'), (1, 'visible'), (0, 'pending')], default=0),
>>>>>>> development
        ),
    ]
