# Generated by Django 4.2.6 on 2023-10-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_ID', models.CharField(max_length=200)),
                ('entry_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TagFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_ID', models.CharField(max_length=200)),
                ('filter_name', models.CharField(max_length=200)),
                ('filter_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntryFilterAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_MTM', models.ManyToManyField(to='Filterer.entries')),
                ('Filter_MTM', models.ManyToManyField(to='Filterer.tagfilters')),
            ],
        ),
    ]
