# Generated by Django 4.2.6 on 2023-10-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filterer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='entry_ID',
        ),
        migrations.RemoveField(
            model_name='tagfilters',
            name='filter_ID',
        ),
        migrations.RemoveField(
            model_name='tagfilters',
            name='filter_desc',
        ),
    ]
