# Generated by Django 4.2.6 on 2023-10-22 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Filterer', '0002_remove_entries_entry_id_remove_tagfilters_filter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='entry_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagfilters',
            name='filter_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
