# Generated by Django 4.2.6 on 2023-10-22 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Filterer', '0003_entries_entry_desc_tagfilters_filter_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryfilterassoc',
            name='AssociationName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
