# Generated by Django 4.2.6 on 2023-12-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0001_initial'),
        ('Filterer', '0004_entryfilterassoc_associationname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entries',
        ),
        migrations.AlterField(
            model_name='entryfilterassoc',
            name='Entry_MTM',
            field=models.ManyToManyField(to='mapViewer.mapwidget'),
        ),
    ]
