# Generated by Django 4.2.6 on 2023-12-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapViewer', '0001_initial'),
        ('Filterer', '0005_delete_entries_alter_entryfilterassoc_entry_mtm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryFilterAssoc',
            new_name='PostFilterAssoc',
        ),
        migrations.RenameModel(
            old_name='TagFilters',
            new_name='PostFilters',
        ),
    ]
