# Generated by Django 4.2.6 on 2024-03-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filterer', '0006_rename_entryfilterassoc_postfilterassoc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFilterAssoc',
        ),
        migrations.DeleteModel(
            name='PostFilters',
        ),
    ]
